### PR TITLE
Fix IDE0058

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fix unused expression errors - https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0058

I have mixed feelings about this one...none of these were actually issues and some of them are pretty weird to be returning values anyways (why does the query builder return itself when appending?)

But not using return values can sometimes indicate a bug (such as not updating a string when doing replace) so I think it's better to have this enabled and deal with a little bit of extra discard code.

### CODE REVIEW

**Comment by chlafreniere** [comment]
Hmm, I'm not so sure about this one. Is there some finer-tuned control that we can use to still prevent some class of issues but not have to put `_ = ` everywhere?

**Comment by Charles-Gagnon** [comment]
I guess we could look into something like what Zi did in https://github.com/Azure/azure-functions-sql-extension/pull/100#pullrequestreview-769403712

But honestly I don't really think it's that huge of a deal. That suppressions file is kind of messy and this kind of stuff isn't going to cause any huge amounts of pain in the end.

**Comment by zijchen** [comment]
> I guess we could look into something like what Zi did in [#100 (review)](https://github.com/Azure/azure-functions-sql-extension/pull/100#pullrequestreview-769403712)
> 
> But honestly I don't really think it's that huge of a deal. That suppressions file is kind of messy and this kind of stuff isn't going to cause any huge amounts of pain in the end.

I auto-generated the suppressions file from Visual Studio. The default is more granular and you need to suppress each occurrence, but I believe you can suppress it at a broader level, like everything under a namespace: https://stackoverflow.com/questions/11359652/suppressmessage-for-a-whole-namespace

**Comment by Charles-Gagnon** [comment]
@chlafreniere @lucyzhang929 What do you think about just not enabling this rule? I'm not sure it's worth the trouble to suppress it or add the extra code to avoid it - the impact is pretty easy to catch and either way we approach the fix (suppress or add discards) results in a bunch of extra stuff. And it's pretty likely more would keep needing to be suppressed as we keep adding stuff which is just going to get even more annoying.

**Comment by chlafreniere** [comment]
> @chlafreniere @lucyzhang929 What do you think about just not enabling this rule? I'm not sure it's worth the trouble to suppress it or add the extra code to avoid it - the impact is pretty easy to catch and either way we approach the fix (suppress or add discards) results in a bunch of extra stuff. And it's pretty likely more would keep needing to be suppressed as we keep adding stuff which is just going to get even more annoying. 

I'm onboard. Let's not enable this one.

**Pull request closed without merging**
